name: MineSkillz
main: me.kyle.youtube.Youtube
version: 3.3
description: Youtube
commands:
  MineSkillz:
    description: Send The Player A Message
  mainrules:
    description: Send The Player A Message
  donate:
    description: Send The Player A Message
  settime:
    description: Send The Player A Message
  ideas:
    description: Send The Player A Message
  website:
    description: Send The Player A Message
  staff:
    description: Send The Player A Message
  news:
    description: Send The Player A Message
  heal:
    description: Send The Player A Message
